#!/bin/sh

set -e

root_dir=$(git rev-parse --show-toplevel)

. "$root_dir/scripts/venv.sh"
set_venv_python "$root_dir"

echo "🚀 Running pre-commit hook 🚀"

files=$(git diff --cached --name-only --diff-filter=d "*.py")

if [ -n "$files" ]; then
  echo -e "\n✨ Sorting imports..."
  "$VENV_PY" -m ruff check --select I --fix $files
  git add $files

  echo -e "\n✨ Linting and formatting..."
  "$VENV_PY" -m ruff check $files
  "$VENV_PY" -m ruff format $files
fi

echo -e "\n🎉 Pre-commit status: success 🎉\n"
